### ISSUE TITLE
Error on running 1.0.7: panic: generate flag redefined: release

### ISSUE THREAD

**Issue by ep4sh** [greenpau/gorpm#14]
Hi! There is an error when trying to run the app:

```
[root@fe2b1f551274 build]# gorpm generate --help
generate flag redefined: release
panic: generate flag redefined: release

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000082900, {0x6262c0, 0xc0000754c0}, {0x5dbf6e, 0x7}, {0x5e65de, 0x1b})
	/usr/local/go/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).StringVar(...)
	/usr/local/go/src/flag/flag.go:762
flag.(*FlagSet).String(0x70a7759b0108?, {0x5dbf6e, 0x7}, {0x0, 0x0}, {0x5e65de, 0x1b})
	/usr/local/go/src/flag/flag.go:775 +0xac
github.com/urfave/cli.StringFlag.ApplyWithError.func1({0x5dbf6e?, 0x7?})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/flag_string.go:67 +0x94
github.com/urfave/cli.eachName({0x5dbf6e?, 0x0?}, 0xc00010f4b8)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/flag.go:130 +0x93
github.com/urfave/cli.StringFlag.ApplyWithError({{0x5dbf6e, 0x7}, {0x5e65de, 0x1b}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/flag_string.go:62 +0xe9
github.com/urfave/cli.flagSet({0x5dd3b6, 0x8}, {0xc0000ea240, 0xa, 0x1?})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/flag.go:115 +0x163
github.com/urfave/cli.(*Command).newFlagSet(...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:216
github.com/urfave/cli.(*Command).parseFlags(0xc0000bcdc0, {0xc0000101a0?, 0x4?, 0x3?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:197 +0xb9
github.com/urfave/cli.Command.Run({{0x5dd3b6, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x5e3cc5, 0x14}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:119 +0x234
github.com/urfave/cli.(*App).Run(0xc00012a000, {0xc000010180, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0x8bb
main.main()
	/go/pkg/mod/github.com/greenpau/gorpm@v1.0.7/cmd/gorpm/main.go:150 +0xa74
```

thanks!

**Comment by iamazy** [comment]
@ep4sh It‘s a bug. You should remove the following code and recompile it.

https://github.com/greenpau/gorpm/blob/3fbe5fe7bf6a1fbfc2de51f4cd5f0dc543017cd7/cmd/gorpm/main.go#L129-L133
